[ 2024-12-27 17:41:34,544 ] 97 werkzeug - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.0.124:5000
[ 2024-12-27 17:41:34,544 ] 97 werkzeug - INFO - [33mPress CTRL+C to quit[0m
[ 2024-12-27 17:42:22,260 ] 97 werkzeug - INFO - 127.0.0.1 - - [27/Dec/2024 17:42:22] "GET / HTTP/1.1" 200 -
[ 2024-12-27 17:42:22,294 ] 97 werkzeug - INFO - 127.0.0.1 - - [27/Dec/2024 17:42:22] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
[ 2024-12-27 17:43:03,965 ] 97 werkzeug - INFO - 127.0.0.1 - - [27/Dec/2024 17:43:03] "GET /predictdata HTTP/1.1" 200 -
[ 2024-12-27 17:45:06,135 ] 838 app - ERROR - Exception on /predictdata [POST]
Traceback (most recent call last):
  File "/home/vishnu-sharma/Desktop/ml/src/pipeline/predict_pipeline.py", line 13, in predict
    model_path=os.path.join("artifacts","model.pkl")
NameError: name 'os' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/vishnu-sharma/.local/lib/python3.8/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/vishnu-sharma/.local/lib/python3.8/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/vishnu-sharma/.local/lib/python3.8/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/vishnu-sharma/.local/lib/python3.8/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "app.py", line 40, in predict_datapoint
    results=predict_pipeline.predict(pred_df)
  File "/home/vishnu-sharma/Desktop/ml/src/pipeline/predict_pipeline.py", line 24, in predict
    raise CustomException(e,sys)
src.exception.CustomException: Error occured in python script name [/home/vishnu-sharma/Desktop/ml/src/pipeline/predict_pipeline.py] line number [13] error message[name 'os' is not defined]
[ 2024-12-27 17:45:06,138 ] 97 werkzeug - INFO - 127.0.0.1 - - [27/Dec/2024 17:45:06] "[35m[1mPOST /predictdata HTTP/1.1[0m" 500 -
